In [1]:
%cd /content/drive/MyDrive

/content/drive/MyDrive


In [4]:
try:
  from transformers import pipeline
except Exception as e:
  print("Instalingg-----")
  !pip install datasets transformers[sentencepiece] -q
  from transformers import pipeline

In [5]:
classifier = pipeline("sentiment-analysis")

No model was supplied, defaulted to distilbert-base-uncased-finetuned-sst-2-english (https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english)


Downloading:   0%|          | 0.00/629 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/255M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/226k [00:00<?, ?B/s]

In [6]:
classifier("I love my country")

[{'label': 'POSITIVE', 'score': 0.9998471736907959}]

In [7]:
classifier(["I love my cointry", "but the movie which i watch yesterday i don't like that"])

[{'label': 'POSITIVE', 'score': 0.9998865127563477},
 {'label': 'NEGATIVE', 'score': 0.9924395084381104}]

In [8]:
classifier("Wayne Knight said it best three decades ago: We got Dodgson here, and nobody cares.")

[{'label': 'NEGATIVE', 'score': 0.7722519040107727}]

In [10]:
review = "Its bad movies galore as we encounter the Rottenest of the Rotten: 100 movies that scored less than 5% with the critics on the Tomatometer!"

In [11]:
classifier(review)

[{'label': 'NEGATIVE', 'score': 0.9997283816337585}]

In [12]:
classifier_zero_shot = pipeline("zero-shot-classification")

No model was supplied, defaulted to facebook/bart-large-mnli (https://huggingface.co/facebook/bart-large-mnli)


Downloading:   0%|          | 0.00/1.13k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.52G [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/878k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/446k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.29M [00:00<?, ?B/s]

In [14]:
classifier_zero_shot(
    "This course is about artificial intelligence, Here we will learn theory and practical both.",
    candidate_labels=["politics", "business", "education"],
)

{'labels': ['education', 'business', 'politics'],
 'scores': [0.4915779232978821, 0.39495235681533813, 0.11346976459026337],
 'sequence': 'This course is about artificial intelligence, Here we will learn theory and practical both.'}

In [20]:
generator = pipeline("text-generation", model="distilgpt2")

Downloading:   0%|          | 0.00/762 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/336M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/0.99M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/446k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.29M [00:00<?, ?B/s]

In [23]:
generator("What is machine learning")

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


[{'generated_text': 'What is machine learning in science and math? It is now an issue, a problem, a problem, and a problem. The reason that learning is no longer a simple task is that it has to be hard and hard, or that learning requires very'}]

In [22]:
generator("This course is about artificial intelligence",
          max_length=40,
          num_return_sequences=3)

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


[{'generated_text': 'This course is about artificial intelligence as well as the way we understand it. We‐ll see what you see in our next talk.\n\n\n\nIf you like the post and want more'},
 {'generated_text': 'This course is about artificial intelligence (AI). The idea is that we may have an artificial intelligence that can understand human actions, like our lives or our social needs. The idea is that we may have'},
 {'generated_text': 'This course is about artificial intelligence, but at most it has become a political question of whether the government has the capacity to prevent real change of the world — or simply whether it does it as a more'}]

In [24]:
generator("the movie was horrible",
          max_length=40,
          num_return_sequences=3)

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


[{'generated_text': 'the movie was horrible), it had been a disaster since it was the first movie.\n\nWhat would have happened if the series had started out as an extended four hour long special?\nIt would'},
 {'generated_text': 'the movie was horrible and all bad,” he said. "So we\'re going back," she said. "But I am sorry."'},
 {'generated_text': 'the movie was horrible, but if you‼re looking forward to it‼, you‥ll have to buy it now. The book is great, and if you enjoyed the movie,'}]

In [25]:
generator("SELECT * FROM TABLE",
          max_length=40,
          num_return_sequences=2)

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


[{'generated_text': 'SELECT * FROM TABLE SELECT SELECT * FROM TABLE WHERE TOP = TOP FROM SELECT SELECT * FROM TABLE WHERE TOP = TOP FROM SELECT * FROM TABLE WHERE TOP = TOP FROM SELECT * FROM TABLE WHERE TOP ='},
 {'generated_text': 'SELECT * FROM TABLE A WHERE A WHERE A TABLE A WHERE A TABLE A WHERE A TABLE A WHERE A TABLE A WHERE A TABLE A WHERE A TABLE A WHERE A TABLE A WHERE TABLE A WHERE A'}]

In [27]:
unamasking = pipeline("fill-mask")

No model was supplied, defaulted to distilroberta-base (https://huggingface.co/distilroberta-base)


Downloading:   0%|          | 0.00/480 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/316M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/878k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/446k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.29M [00:00<?, ?B/s]

In [30]:
unamasking("This course is about <mask> data)", top_k=8)

[{'score': 0.15197759866714478,
  'sequence': 'This course is about collecting data)',
  'token': 8664,
  'token_str': ' collecting'},
 {'score': 0.07670345902442932,
  'sequence': 'This course is about analyzing data)',
  'token': 18999,
  'token_str': ' analyzing'},
 {'score': 0.05548069253563881,
  'sequence': 'This course is about raw data)',
  'token': 6087,
  'token_str': ' raw'},
 {'score': 0.03354529291391373,
  'sequence': 'This course is about interpreting data)',
  'token': 37212,
  'token_str': ' interpreting'},
 {'score': 0.029122482985258102,
  'sequence': 'This course is about gathering data)',
  'token': 5660,
  'token_str': ' gathering'},
 {'score': 0.026393935084342957,
  'sequence': 'This course is about big data)',
  'token': 380,
  'token_str': ' big'},
 {'score': 0.019139248877763748,
  'sequence': 'This course is about getting data)',
  'token': 562,
  'token_str': ' getting'},
 {'score': 0.014566609635949135,
  'sequence': 'This course is about empirical data)',

In [34]:
NER = pipeline("ner", grouped_entities=True)

No model was supplied, defaulted to dbmdz/bert-large-cased-finetuned-conll03-english (https://huggingface.co/dbmdz/bert-large-cased-finetuned-conll03-english)
/usr/local/lib/python3.7/dist-packages/transformers/pipelines/token_classification.py:136: UserWarning: `grouped_entities` is deprecated and will be removed in version v5.0.0, defaulted to `aggregation_strategy="AggregationStrategy.SIMPLE"` instead.
  f'`grouped_entities` is deprecated and will be removed in version v5.0.0, defaulted to `aggregation_strategy="{aggregation_strategy}"` instead.'


In [36]:
NER("I am narender and I am working at teleperformance")

[]

In [37]:
QA = pipeline("question-answering")

No model was supplied, defaulted to distilbert-base-cased-distilled-squad (https://huggingface.co/distilbert-base-cased-distilled-squad)


Downloading:   0%|          | 0.00/473 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/249M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/29.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/208k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/426k [00:00<?, ?B/s]

In [41]:
QA(
    
    question="Where do i live? ",
    context="I am Narender and I work in Teleperformance. I live in Bangalore."
)

{'answer': 'Bangalore', 'end': 64, 'score': 0.9855759739875793, 'start': 55}

In [42]:
!pip install gradio -q

     |████████████████████████████████| 5.1 MB 8.2 MB/s 
     |████████████████████████████████| 2.0 MB 74.6 MB/s 
     |████████████████████████████████| 54 kB 2.7 MB/s 
     |████████████████████████████████| 256 kB 71.3 MB/s 
     |████████████████████████████████| 53 kB 2.4 MB/s 
     |████████████████████████████████| 212 kB 62.7 MB/s 
     |████████████████████████████████| 84 kB 3.0 MB/s 
     |████████████████████████████████| 63 kB 2.3 MB/s 
     |████████████████████████████████| 11.1 MB 56.2 MB/s 
     |████████████████████████████████| 80 kB 10.0 MB/s 
     |████████████████████████████████| 43 kB 2.4 MB/s 
     |████████████████████████████████| 856 kB 51.3 MB/s 
     |████████████████████████████████| 4.0 MB 52.5 MB/s 
     |████████████████████████████████| 62 kB 1.1 MB/s 
     |████████████████████████████████| 58 kB 6.8 MB/s 


In [44]:
summarization = pipeline("summarization")

No model was supplied, defaulted to sshleifer/distilbart-cnn-12-6 (https://huggingface.co/sshleifer/distilbart-cnn-12-6)


Downloading:   0%|          | 0.00/1.76k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.14G [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/878k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/446k [00:00<?, ?B/s]

In [45]:
in_text = """Gradio is an open-source Python library that is used to build machine learning and data science demos and web applications.
With Gradio, you can quickly create a beautiful user interface around your machine learning models or data science workflow and let people "try it out" by dragging-and-dropping in their own images, pasting text, recording their own voice, and interacting with your demo, all through the browser."""

summarization(in_text, max_length=56)

[{'summary_text': ' Gradio is an open-source Python library that is used to build machine learning and data science demos and web applications . With Gradio, you can quickly create a beautiful user interface around your machine learning models or data science workflow and let people "try it out"'}]

In [46]:
translator = pipeline('translation', model="Helsinki-NLP/opus-mt-fr-en")

Downloading:   0%|          | 0.00/1.26k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/287M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/42.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/784k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/760k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.28M [00:00<?, ?B/s]

/usr/local/lib/python3.7/dist-packages/transformers/models/marian/tokenization_marian.py:196: UserWarning: Recommended: pip install sacremoses.
  warnings.warn("Recommended: pip install sacremoses.")


In [47]:
translator("je bois du lait")

[{'translation_text': 'I drink milk'}]

In [49]:
unamasking("This man is <mask>")

[{'score': 0.07179437577724457,
  'sequence': 'This man is:',
  'token': 35,
  'token_str': ':'},
 {'score': 0.059049855917692184,
  'sequence': 'This man is autistic',
  'token': 33329,
  'token_str': ' autistic'},
 {'score': 0.05104430392384529,
  'sequence': 'This man is...',
  'token': 734,
  'token_str': '...'},
 {'score': 0.04487407207489014,
  'sequence': 'This man is missing',
  'token': 1716,
  'token_str': ' missing'},
 {'score': 0.03603643178939819,
  'sequence': 'This man is unavailable',
  'token': 19216,
  'token_str': ' unavailable'}]

In [50]:
generator("This black man is")

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


[{'generated_text': 'This black man is alive & well, that has nothing to do with all of this — there was some big deal of drama. I\u200fm sorry this was a week for me, but I’m sorry I’m not an'}]

In [52]:
generated_text = generator("This black man is")[0]["generated_text"]

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


In [53]:
classifier(generated_text)

[{'label': 'NEGATIVE', 'score': 0.9722520112991333}]

In [54]:
classifier_zero_shot(
    generated_text,
    candidate_labels=["biased", "unbiased", "racist"],
)

{'labels': ['biased', 'racist', 'unbiased'],
 'scores': [0.6170292496681213, 0.2981451153755188, 0.0848255529999733],
 'sequence': 'This black man is just beginning to get out of his way, he may be the most infamous person in a long time. The man who is now in jail in Kansas City accused of murdering two women allegedly killed while a child was playing at Play-'}

In [ ]:
#####

In [55]:
try:
  from transformers import pipeline
except Exception as e:
  print(e)
  print("installing...")
  !pip install datasets transformers[sentencepiece] -q
  from transformers import pipeline

In [56]:
import torch
torch.cuda.is_available()

True

In [57]:
%%timeit
classifier = pipeline("sentiment-analysis")
classifier("I love my country")

No model was supplied, defaulted to distilbert-base-uncased-finetuned-sst-2-english (https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english)
No model was supplied, defaulted to distilbert-base-uncased-finetuned-sst-2-english (https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english)
No model was supplied, defaulted to distilbert-base-uncased-finetuned-sst-2-english (https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english)
No model was supplied, defaulted to distilbert-base-uncased-finetuned-sst-2-english (https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english)
No model was supplied, defaulted to distilbert-base-uncased-finetuned-sst-2-english (https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english)
No model was supplied, defaulted to distilbert-base-uncased-finetuned-sst-2-english (https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english)


1 loop, best of 5: 4.16 s per loop


In [59]:
from transformers import AutoTokenizer

In [62]:
ckpt = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer=AutoTokenizer.from_pretrained(ckpt)

In [63]:
inputs = "I love my country"

In [64]:
tokenizer(inputs)

{'input_ids': [101, 1045, 2293, 2026, 2406, 102], 'attention_mask': [1, 1, 1, 1, 1, 1]}

In [67]:
batch_input = ["I love my country",
               "I am Sunny and I work in iNeuron"]

In [68]:
out = tokenizer(batch_input, padding=True)
out

{'input_ids': [[101, 1045, 2293, 2026, 2406, 102, 0, 0, 0, 0, 0, 0], [101, 1045, 2572, 11559, 1998, 1045, 2147, 1999, 1999, 11236, 2239, 102]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]}

In [69]:
out_pytorch_tensors = tokenizer(batch_input, padding=True, return_tensors="pt")
out_pytorch_tensors

{'input_ids': tensor([[  101,  1045,  2293,  2026,  2406,   102,     0,     0,     0,     0,
             0,     0],
        [  101,  1045,  2572, 11559,  1998,  1045,  2147,  1999,  1999, 11236,
          2239,   102]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [70]:
out_TF_tensors = tokenizer(batch_input, padding=True, return_tensors="tf")
out_TF_tensors

{'input_ids': <tf.Tensor: shape=(2, 12), dtype=int32, numpy=
array([[  101,  1045,  2293,  2026,  2406,   102,     0,     0,     0,
            0,     0,     0],
       [  101,  1045,  2572, 11559,  1998,  1045,  2147,  1999,  1999,
        11236,  2239,   102]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(2, 12), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)>}

In [71]:
from transformers import AutoModel

In [72]:
model_ckpt = AutoModel.from_pretrained(ckpt)

Some weights of the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english were not used when initializing DistilBertModel: ['pre_classifier.weight', 'pre_classifier.bias', 'classifier.bias', 'classifier.weight']
- This IS expected if you are initializing DistilBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DistilBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [73]:
model_ckpt

DistilBertModel(
  (embeddings): Embeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (transformer): Transformer(
    (layer): ModuleList(
      (0): TransformerBlock(
        (attention): MultiHeadSelfAttention(
          (dropout): Dropout(p=0.1, inplace=False)
          (q_lin): Linear(in_features=768, out_features=768, bias=True)
          (k_lin): Linear(in_features=768, out_features=768, bias=True)
          (v_lin): Linear(in_features=768, out_features=768, bias=True)
          (out_lin): Linear(in_features=768, out_features=768, bias=True)
        )
        (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        (ffn): FFN(
          (dropout): Dropout(p=0.1, inplace=False)
          (lin1): Linear(in_features=768, out_features=3072, bias=True)
          (lin2): Linear(i